version: "2"
services:
  jupyter-lab:
    build:
      context: docker
      dockerfile: Dockerfile
    ports:
      - "8080:8888"
    volumes:
      - ./.jupyter:/home/jovyan/.jupyter
      - ./notebooks:/home/jovyan/notebooks
      - ./datasets:/home/jovyan/datasets
      - ./results:/home/jovyan/results
      - ./plots:/home/jovyan/plots
      - ./API:/home/jovyan/API
      - ./models:/home/jovyan/models
    command:
      - --no-browser
      - --ip=0.0.0.0
